import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import { STLLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/STLLoader.js';
import { OBJLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/OBJLoader.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
import { mergeGeometries, mergeVertices } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/utils/BufferGeometryUtils.js';

const APP_VERSION='5.0', $=id=>document.getElementById(id);
let scene,camera,renderer,controls,scanMesh,cadGroup,geometry,currentStep=0,reloading=false;
let axes={z:null,x:null,y:null}, selectedFaces=[], selectedPoints=[], featureMode='line', activeView='scan';
const planes={z:[],x:[],y:[]},features=[];let planeSeq=1;

init();bind();registerPWA();
function init(){
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.01,100000);camera.position.set(2.4,1.7,2.8);
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;$('viewer').appendChild(renderer.domElement);
 controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;
 scene.add(new THREE.HemisphereLight(0xffffff,0x26313f,2.2));const dl=new THREE.DirectionalLight(0xffffff,2.4);dl.position.set(3,5,4);scene.add(dl);const grid=new THREE.GridHelper(10,20,0x435267,0x222b36);grid.name='grid';scene.add(grid);
 const resize=()=>{const v=$('viewer'),w=v.clientWidth||1,h=v.clientHeight||1;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};new ResizeObserver(resize).observe($('viewer'));resize();
 renderer.domElement.addEventListener('pointerdown',pick);
 (function tick(){controls.update();renderer.render(scene,camera);requestAnimationFrame(tick)})();
}
function bind(){
 $('openBtn').onclick=()=>$('fileInput').click();$('changeBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=()=>$('fileInput').files[0]&&loadFile($('fileInput').files[0]);$('fitBtn').onclick=fit;$('wireBtn').onclick=()=>{if(scanMesh){scanMesh.material.wireframe=!scanMesh.material.wireframe;scanMesh.material.needsUpdate=true}};
 $('clearSelection').onclick=clearSelection;$('defineZ').onclick=()=>defineAxis('z');$('defineX').onclick=()=>defineAxis('x');$('addZPlane').onclick=()=>savePlane('z');$('addXPlane').onclick=()=>savePlane('x');$('addYPlane').onclick=()=>savePlane('y');$('saveFeature').onclick=saveFeature;$('buildCad').onclick=buildCad;
 $('scanView').onclick=()=>setView('scan');$('cadView').onclick=()=>setView('cad');$('overlayView').onclick=()=>setView('overlay');$('prevStep').onclick=()=>goStep(currentStep-1);$('nextStep').onclick=()=>goStep(currentStep+1);
 document.querySelectorAll('#wizardTabs button').forEach(b=>b.onclick=()=>goStep(+b.dataset.step));document.querySelectorAll('.feature-buttons button').forEach(b=>b.onclick=()=>{featureMode=b.dataset.feature;selectedPoints=[];document.querySelectorAll('.feature-buttons button').forEach(x=>x.classList.toggle('active',x===b));updateFeatureStatus()});
}
function registerPWA(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()});window.addEventListener('load',async()=>{try{const r=await navigator.serviceWorker.register(`./sw.js?v=${APP_VERSION}`,{updateViaCache:'none'});await r.update();if(r.waiting)r.waiting.postMessage({type:'SKIP_WAITING'})}catch(e){console.warn(e)}})}
async function loadGLTF(buf,ext){const l=new GLTFLoader(),payload=ext==='gltf'?new TextDecoder().decode(buf):buf,gltf=await new Promise((res,rej)=>l.parse(payload,'',res,rej));gltf.scene.updateMatrixWorld(true);const gs=[];gltf.scene.traverse(c=>{if(!c.isMesh||!c.geometry?.attributes?.position)return;let g=c.geometry.clone();if(g.index)g=g.toNonIndexed();const f=new THREE.BufferGeometry();f.setAttribute('position',g.attributes.position.clone());f.applyMatrix4(c.matrixWorld);gs.push(f)});if(!gs.length)throw new Error('No hay meshes.');return gs.length===1?gs[0]:mergeGeometries(gs,false)}
async function loadFile(file){busy(true,'Abriendo modelo');try{const ext=file.name.split('.').pop().toLowerCase(),buf=await file.arrayBuffer();let g;if(ext==='stl')g=new STLLoader().parse(buf);else if(ext==='obj'){const o=new OBJLoader().parse(new TextDecoder().decode(buf));o.updateMatrixWorld(true);const gs=[];o.traverse(c=>{if(c.isMesh&&c.geometry?.attributes?.position){const x=new THREE.BufferGeometry();x.setAttribute('position',c.geometry.attributes.position.clone());x.applyMatrix4(c.matrixWorld);gs.push(x)}});g=gs.length===1?gs[0]:mergeGeometries(gs,false)}else if(ext==='glb'||ext==='gltf')g=await loadGLTF(buf,ext);else throw new Error('Formato no compatible.');
 g=normalize(g);clearModel();geometry=g;scanMesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0xe7edf3,roughness:.76,metalness:0,side:THREE.DoubleSide}));scene.add(scanMesh);$('dropHint').classList.add('hidden');$('hud').classList.remove('hidden');$('fileName').textContent=file.name;const f=g.index?g.index.count/3:g.attributes.position.count/3;$('meshStats').textContent=`${g.attributes.position.count.toLocaleString('es-AR')} vértices · ${Math.round(f).toLocaleString('es-AR')} caras`;$('changeBtn').disabled=false;$('scanView').disabled=false;goStep(0);fit();
 }catch(e){alert(`No pude abrir el modelo: ${e.message}`)}finally{busy(false)}}
function normalize(input){let g=new THREE.BufferGeometry();g.setAttribute('position',input.attributes.position.clone());g=mergeVertices(g,1e-5);g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g}
function clearModel(){if(scanMesh){scene.remove(scanMesh);scanMesh.material.dispose()}if(cadGroup)scene.remove(cadGroup);scanMesh=null;cadGroup=null;geometry?.dispose();geometry=null;axes={z:null,x:null,y:null};planes.z=[];planes.x=[];planes.y=[];features.length=0;clearSelection();renderAllLists()}
function pick(ev){if(!scanMesh||activeView==='cad')return;const r=renderer.domElement.getBoundingClientRect(),m=new THREE.Vector2((ev.clientX-r.left)/r.width*2-1,-((ev.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(m,camera);const hit=ray.intersectObject(scanMesh,false)[0];if(!hit)return;
 if(currentStep<=3){const face=hit.faceIndex;if(face==null)return;if(!selectedFaces.includes(face))selectedFaces.push(face);addMarker(hit.point);updateSelection()}else if(currentStep===4){selectedPoints.push(hit.point.clone());addMarker(hit.point,0x66ddff);updateFeatureStatus()}}
function addMarker(p,color=0xffb347){const s=geometry?.boundingSphere?.radius||1,g=new THREE.SphereGeometry(s*.008,10,8),m=new THREE.MeshBasicMaterial({color,depthTest:false}),o=new THREE.Mesh(g,m);o.position.copy(p);o.renderOrder=20;o.userData.selectionMarker=true;scene.add(o)}
function clearMarkers(){scene.children.filter(o=>o.userData.selectionMarker).forEach(o=>{scene.remove(o);o.geometry?.dispose();o.material?.dispose()})}
function clearSelection(){selectedFaces=[];selectedPoints=[];clearMarkers();updateSelection();updateFeatureStatus()}
function updateSelection(){$('selectionCount').textContent=`${selectedFaces.length} caras seleccionadas`;$('defineZ').disabled=!geometry||!selectedFaces.length;$('defineX').disabled=!geometry||!selectedFaces.length}
function faceNormalWorld(fi){const idx=geometry.index.array,p=geometry.attributes.position.array,a=idx[fi*3]*3,b=idx[fi*3+1]*3,c=idx[fi*3+2]*3,A=new THREE.Vector3(p[a],p[a+1],p[a+2]),B=new THREE.Vector3(p[b],p[b+1],p[b+2]),C=new THREE.Vector3(p[c],p[c+1],p[c+2]);return B.sub(A).cross(C.sub(A)).normalize()}
function faceCenter(fi){const idx=geometry.index.array,p=geometry.attributes.position.array,a=idx[fi*3]*3,b=idx[fi*3+1]*3,c=idx[fi*3+2]*3;return new THREE.Vector3((p[a]+p[b]+p[c])/3,(p[a+1]+p[b+1]+p[c+1])/3,(p[a+2]+p[b+2]+p[c+2])/3)}
function averageSelectedNormal(){const n=new THREE.Vector3();for(const f of selectedFaces){const x=faceNormalWorld(f);if(n.lengthSq()&&n.dot(x)<0)x.negate();n.add(x)}return n.normalize()}
function defineAxis(axis){let n=averageSelectedNormal();if(!n.lengthSq())return;if(axis==='z'){axes.z=n.clone();axes.x=null;axes.y=null}else{if(!axes.z)return alert('Definí Z primero.');n.addScaledVector(axes.z,-n.dot(axes.z)).normalize();axes.x=n;axes.y=new THREE.Vector3().crossVectors(axes.z,axes.x).normalize();axes.x=new THREE.Vector3().crossVectors(axes.y,axes.z).normalize()}clearSelection();updateAxisStatus();}
function updateAxisStatus(){const arr=[];if(axes.z)arr.push('Z definido');if(axes.x)arr.push('X definido');if(axes.y)arr.push('Y calculado');$('axisStatus').innerHTML=arr.map(x=>`<span>${x}</span>`).join('');}
function axisVector(kind){return axes[kind]}
function savePlane(kind){const axis=axisVector(kind);if(!axis)return alert(`Primero definí el eje ${kind.toUpperCase()}.`);if(!selectedFaces.length)return alert('Tocá 1–3 caras de esa superficie.');const vals=selectedFaces.map(f=>faceCenter(f).dot(axis)).sort((a,b)=>a-b),coord=vals[Math.floor(vals.length/2)];extractPlane(kind,axis,coord,selectedFaces.slice())}
function extractPlane(kind,axis,coord,seeds){busy(true,`Extrayendo plano ${kind.toUpperCase()}`);const pos=new Float32Array(geometry.attributes.position.array),idx=geometry.index.array.constructor.from(geometry.index.array),w=new Worker(`./assisted-worker.js?v=${APP_VERSION}`);w.onmessage=({data})=>{if(data.type==='progress'){$('busyStage').textContent=data.stage;return}if(data.type==='error'){w.terminate();busy(false);alert(data.message);return}if(data.type==='done'){const pl={id:planeSeq++,kind,...data.plane};planes[kind].push(pl);w.terminate();busy(false);clearSelection();renderPlaneList(kind);refreshFeaturePlane();addPlanePreview(pl)}};w.onerror=()=>{w.terminate();busy(false);alert('Falló la extracción del plano.')};w.postMessage({type:'extractPlane',positions:pos,indices:idx,axis:[axis.x,axis.y,axis.z],coord,seedFaces:seeds,angleDeg:18,simplifyTol:(geometry.boundingSphere.radius||1)*.002},[pos.buffer,idx.buffer])}
function addPlanePreview(pl){const g=shapeGeometry(pl),m=new THREE.MeshBasicMaterial({color:pl.kind==='z'?0x65b7ff:pl.kind==='x'?0xff9f68:0x85e29b,transparent:true,opacity:.22,side:THREE.DoubleSide,depthWrite:false}),mesh=new THREE.Mesh(g,m);mesh.userData.planePreview=true;scene.add(mesh)}
function shapeGeometry(pl){const shape=new THREE.Shape(pl.outer.map(q=>new THREE.Vector2(q[0],q[1])));for(const h of pl.holes||[]){const path=new THREE.Path(h.map(q=>new THREE.Vector2(q[0],q[1])));shape.holes.push(path)}const g=new THREE.ShapeGeometry(shape);const p=g.attributes.position;for(let i=0;i<p.count;i++){const a=p.getX(i),b=p.getY(i),o=pl.origin,u=pl.u,v=pl.v;p.setXYZ(i,o[0]+u[0]*a+v[0]*b,o[1]+u[1]*a+v[1]*b,o[2]+u[2]*a+v[2]*b)}g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g}
function renderPlaneList(kind){const box=$(`${kind}Planes`);box.innerHTML=planes[kind].map((p,i)=>`<div class="plane-item"><span>${kind.toUpperCase()}${i+1} · ${p.acceptedFaces} caras</span><button data-del="${p.id}">×</button></div>`).join('');box.querySelectorAll('button').forEach(b=>b.onclick=()=>deletePlane(+b.dataset.del))}
function deletePlane(id){for(const k of['z','x','y']){const i=planes[k].findIndex(p=>p.id===id);if(i>=0){planes[k].splice(i,1);break}}scene.children.filter(o=>o.userData.planePreview).forEach(o=>{scene.remove(o);o.geometry.dispose();o.material.dispose()});for(const k of['z','x','y'])for(const p of planes[k])addPlanePreview(p);renderAllLists();refreshFeaturePlane()}
function renderAllLists(){for(const k of['z','x','y'])renderPlaneList(k);renderFeatureList();refreshFeaturePlane();updateAxisStatus()}
function refreshFeaturePlane(){const s=$('featurePlane'),all=[...planes.z,...planes.x,...planes.y];s.innerHTML=all.map(p=>`<option value="${p.id}">${p.kind.toUpperCase()}${planes[p.kind].indexOf(p)+1}</option>`).join('')}
function updateFeatureStatus(){$('featureStatus').textContent=`${selectedPoints.length} puntos seleccionados · ${featureMode}`}
function saveFeature(){const need=featureMode==='line'?2:3;if(selectedPoints.length<need)return alert(`Necesito ${need} puntos.`);const pid=+$('featurePlane').value;if(!pid)return alert('Primero guardá y elegí un plano.');features.push({id:features.length+1,planeId:pid,type:featureMode,points:selectedPoints.slice(0,need).map(p=>[p.x,p.y,p.z])});selectedPoints=[];clearMarkers();updateFeatureStatus();renderFeatureList()}
function renderFeatureList(){$('featureList').innerHTML=features.map(f=>`<div class="plane-item"><span>${f.type} · plano #${f.planeId}</span></div>`).join('')}
function buildCad(){if(![...planes.z,...planes.x,...planes.y].length)return alert('Guardá algunos planos primero.');if(cadGroup)scene.remove(cadGroup);cadGroup=new THREE.Group();for(const pl of[...planes.z,...planes.x,...planes.y]){const g=shapeGeometry(pl),m=new THREE.MeshStandardMaterial({color:0xc7d4df,roughness:.5,metalness:.02,side:THREE.DoubleSide}),o=new THREE.Mesh(g,m);cadGroup.add(o)}scene.add(cadGroup);$('cadView').disabled=false;$('overlayView').disabled=false;$('cadSummary').innerHTML=`<span>${cadGroup.children.length} superficies CAD</span><span>${features.length} features marcadas</span>`;setView('cad')}
function setView(v){activeView=v;if(scanMesh)scanMesh.visible=v!=='cad';if(cadGroup)cadGroup.visible=v!=='scan';if(scanMesh){scanMesh.material.transparent=v==='overlay';scanMesh.material.opacity=v==='overlay'?.28:1;scanMesh.material.depthWrite=v!=='overlay'}[['scanView','scan'],['cadView','cad'],['overlayView','overlay']].forEach(([id,x])=>$(id).classList.toggle('active',v===x))}
function goStep(n){currentStep=Math.max(0,Math.min(6,n));document.querySelectorAll('.step').forEach((s,i)=>s.classList.toggle('active',i===currentStep));document.querySelectorAll('#wizardTabs button').forEach((b,i)=>b.classList.toggle('active',i===currentStep));$('prevStep').disabled=currentStep===0;$('nextStep').disabled=currentStep===6;clearSelection();}
function fit(){if(!geometry?.boundingBox)return;const box=geometry.boundingBox.clone(),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),max=Math.max(size.x,size.y,size.z)||1,dist=max/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov*.5)));camera.near=Math.max(max/10000,.001);camera.far=max*100;camera.position.copy(center).add(new THREE.Vector3(1,.72,1).normalize().multiplyScalar(dist*1.7));camera.updateProjectionMatrix();controls.target.copy(center);controls.update();const grid=scene.getObjectByName('grid');if(grid){grid.scale.setScalar(max/10);grid.position.y=box.min.y-max*.02}}
function busy(on,text='Procesando…'){$('busy').classList.toggle('hidden',!on);$('busyStage').textContent=text}
