import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import { STLLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/STLLoader.js';
import { OBJLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/OBJLoader.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
import { STLExporter } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/exporters/STLExporter.js';
import { OBJExporter } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/exporters/OBJExporter.js';
import { mergeGeometries, mergeVertices } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/utils/BufferGeometryUtils.js';

const APP_VERSION='4.0';
const $=id=>document.getElementById(id);
const ids=['viewer','fileInput','openBtn','changeBtn','analyzeBtn','resetBtn','exportStlBtn','exportObjBtn','originalView','cleanView','busy','busyStage','dropHint','viewerHud','fileName','meshStats','resultCard','resultText','cadFacts','installBtn','versionBadge','rebuildEngineTab','cadEngineTab','legacyEngineTab','rebuildControls','cadControls','legacyControls','rebuildTilted','rebuildAngle','rebuildAngleValue','rebuildConfidence','rebuildConfidenceValue','rebuildMinRegion','rebuildMinRegionValue','rebuildSimplify','rebuildSimplifyValue','strength','strengthValue','angle','angleValue','confidence','confidenceValue','minRegion','regionValue','allowTiltedPlanes','alignParallel','orthogonalSnap','sharpIntersections','detectThickness','edgeProtect','edgeValue','legacyStrength','legacyStrengthValue','legacyAngle','legacyAngleValue','legacyMinRegion','legacyRegionValue'];
const e={};ids.forEach(id=>e[id]=$(id));e.versionBadge.textContent=`v${APP_VERSION}`;
let scene,camera,renderer,controls,displayMesh=null,originalGeometry=null,resultGeometry=null,activeName='modelo',engine='rebuild',deferredInstallPrompt=null,reloadingForUpdate=false,duplicateFacesRemoved=0;
init3D();registerPWA();bindUI();

function mat(){return new THREE.MeshStandardMaterial({color:0xe7edf3,roughness:.72,metalness:.02,side:THREE.DoubleSide})}
function init3D(){scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.01,100000);camera.position.set(2.4,1.7,2.8);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;e.viewer.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;scene.add(new THREE.HemisphereLight(0xffffff,0x273445,2.1));const key=new THREE.DirectionalLight(0xffffff,2.3);key.position.set(2,4,3);scene.add(key);const rim=new THREE.DirectionalLight(0x92bfff,1.1);rim.position.set(-3,1,-2);scene.add(rim);const grid=new THREE.GridHelper(10,20,0x415165,0x222b36);grid.name='grid';scene.add(grid);const resize=()=>{const w=e.viewer.clientWidth||1,h=e.viewer.clientHeight||1;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};new ResizeObserver(resize).observe(e.viewer);resize();(function tick(){controls.update();renderer.render(scene,camera);requestAnimationFrame(tick)})()}
function registerPWA(){if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloadingForUpdate)return;reloadingForUpdate=true;location.reload()});window.addEventListener('load',async()=>{try{const r=await navigator.serviceWorker.register(`./sw.js?v=${APP_VERSION}`,{updateViaCache:'none'});await r.update();if(r.waiting)r.waiting.postMessage({type:'SKIP_WAITING'});r.addEventListener('updatefound',()=>{const w=r.installing;if(w)w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)w.postMessage({type:'SKIP_WAITING'})})})}catch(err){console.warn(err)}})}window.addEventListener('beforeinstallprompt',x=>{x.preventDefault();deferredInstallPrompt=x;e.installBtn.classList.remove('hidden')});e.installBtn.onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;e.installBtn.classList.add('hidden')}}
function bindUI(){e.openBtn.onclick=()=>e.fileInput.click();e.changeBtn.onclick=()=>e.fileInput.click();e.fileInput.onchange=()=>e.fileInput.files[0]&&loadFile(e.fileInput.files[0]);$('fitBtn').onclick=fitCamera;$('wireBtn').onclick=()=>{if(displayMesh){displayMesh.material.wireframe=!displayMesh.material.wireframe;displayMesh.material.needsUpdate=true}};e.originalView.onclick=()=>show('original');e.cleanView.onclick=()=>show('result');e.rebuildEngineTab.onclick=()=>setEngine('rebuild');e.cadEngineTab.onclick=()=>setEngine('cad');e.legacyEngineTab.onclick=()=>setEngine('legacy');e.analyzeBtn.onclick=runEngine;e.resetBtn.onclick=resetResult;e.exportStlBtn.onclick=exportSTL;e.exportObjBtn.onclick=exportOBJ;[[e.rebuildAngle,e.rebuildAngleValue,'°'],[e.rebuildConfidence,e.rebuildConfidenceValue,'%'],[e.rebuildMinRegion,e.rebuildMinRegionValue,' caras'],[e.rebuildSimplify,e.rebuildSimplifyValue,'%'],[e.strength,e.strengthValue,'%'],[e.angle,e.angleValue,'°'],[e.confidence,e.confidenceValue,'%'],[e.minRegion,e.regionValue,' caras'],[e.edgeProtect,e.edgeValue,'%'],[e.legacyStrength,e.legacyStrengthValue,'%'],[e.legacyAngle,e.legacyAngleValue,'°'],[e.legacyMinRegion,e.legacyRegionValue,' caras']].forEach(([a,b,s])=>a.oninput=()=>b.value=`${a.value}${s}`);['dragenter','dragover'].forEach(t=>e.viewer.addEventListener(t,x=>{x.preventDefault();e.viewer.parentElement.classList.add('dragging')}));['dragleave','drop'].forEach(t=>e.viewer.addEventListener(t,x=>{x.preventDefault();e.viewer.parentElement.classList.remove('dragging')}));e.viewer.addEventListener('drop',x=>{const f=x.dataTransfer.files[0];if(f)loadFile(f)})}
function setEngine(mode){engine=mode;e.rebuildEngineTab.classList.toggle('active',mode==='rebuild');e.cadEngineTab.classList.toggle('active',mode==='cad');e.legacyEngineTab.classList.toggle('active',mode==='legacy');e.rebuildControls.classList.toggle('hidden',mode!=='rebuild');e.cadControls.classList.toggle('hidden',mode!=='cad');e.legacyControls.classList.toggle('hidden',mode!=='legacy');e.analyzeBtn.textContent=mode==='rebuild'?'Rebuild CAD':mode==='cad'?'Mesh → CAD':'Aplicar Planar Cleanup';resetResult();setEnabled(!!originalGeometry)}
async function loadGLTF(buffer,ext){const loader=new GLTFLoader(),payload=ext==='gltf'?new TextDecoder().decode(buffer):buffer,gltf=await new Promise((res,rej)=>loader.parse(payload,'',res,rej));gltf.scene.updateMatrixWorld(true);const gs=[];gltf.scene.traverse(c=>{if(!c.isMesh||!c.geometry?.attributes?.position)return;let g=c.geometry.clone();if(g.index)g=g.toNonIndexed();const f=new THREE.BufferGeometry();f.setAttribute('position',g.attributes.position.clone());f.applyMatrix4(c.matrixWorld);gs.push(f)});if(!gs.length)throw new Error('El GLB/GLTF no contiene meshes.');return gs.length===1?gs[0]:mergeGeometries(gs,false)}
async function loadFile(file){const ext=file.name.split('.').pop().toLowerCase();if(!['stl','obj','glb','gltf'].includes(ext))return alert('3DLab acepta GLB, GLTF, STL y OBJ.');busy(true,'Abriendo modelo');try{const buffer=await file.arrayBuffer();let g;if(ext==='stl')g=new STLLoader().parse(buffer);else if(ext==='obj'){const obj=new OBJLoader().parse(new TextDecoder().decode(buffer));obj.updateMatrixWorld(true);const gs=[];obj.traverse(c=>{if(!c.isMesh||!c.geometry?.attributes?.position)return;const x=new THREE.BufferGeometry();x.setAttribute('position',c.geometry.attributes.position.clone());x.applyMatrix4(c.matrixWorld);gs.push(x)});if(!gs.length)throw new Error('El OBJ no contiene meshes.');g=gs.length===1?gs[0]:mergeGeometries(gs,false)}else g=await loadGLTF(buffer,ext);g=normalize(g);clearModel();originalGeometry=g;activeName=file.name.replace(/\.[^.]+$/,'');displayMesh=new THREE.Mesh(originalGeometry,mat());scene.add(displayMesh);e.dropHint.classList.add('hidden');e.viewerHud.classList.remove('hidden');e.fileName.textContent=file.name;stats();setEnabled(true);e.cleanView.disabled=true;e.exportStlBtn.disabled=true;e.exportObjBtn.disabled=true;e.resultCard.classList.add('hidden');show('original');fitCamera()}catch(err){console.error(err);alert(`No pude abrir el modelo: ${err.message}`)}finally{busy(false)}}
function normalize(input){let g=new THREE.BufferGeometry();g.setAttribute('position',input.attributes.position.clone());g=mergeVertices(g,1e-5);const d=dedup(g);duplicateFacesRemoved=d.removed;g=d.geometry;g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g}
function dedup(g){if(!g.index)return{geometry:g,removed:0};const idx=g.index.array,seen=new Set(),out=[];let removed=0;for(let i=0;i<idx.length;i+=3){const a=idx[i],b=idx[i+1],c=idx[i+2];if(a===b||b===c||a===c){removed++;continue}const s=[a,b,c].sort((x,y)=>x-y),k=`${s[0]},${s[1]},${s[2]}`;if(seen.has(k)){removed++;continue}seen.add(k);out.push(a,b,c)}if(!removed)return{geometry:g,removed:0};const ng=g.clone(),Ctor=g.attributes.position.count>65535?Uint32Array:Uint16Array;ng.setIndex(new THREE.BufferAttribute(new Ctor(out),1));g.dispose();return{geometry:ng,removed}}
function clearModel(){if(displayMesh){scene.remove(displayMesh);displayMesh.material.dispose();displayMesh=null}originalGeometry?.dispose();resultGeometry?.dispose();originalGeometry=resultGeometry=null}
function show(which){if(!displayMesh)return;const g=which==='result'&&resultGeometry?resultGeometry:originalGeometry;if(!g)return;displayMesh.geometry=g;e.originalView.classList.toggle('active',which!=='result');e.cleanView.classList.toggle('active',which==='result')}
function install(g){resultGeometry?.dispose();resultGeometry=g;e.cleanView.disabled=false;e.exportStlBtn.disabled=false;e.exportObjBtn.disabled=false;show('result');fitCamera()}
function resetResult(){resultGeometry?.dispose();resultGeometry=null;if(originalGeometry)show('original');e.cleanView.disabled=true;e.exportStlBtn.disabled=true;e.exportObjBtn.disabled=true;e.resultCard.classList.add('hidden')}
function setEnabled(v){[e.changeBtn,e.analyzeBtn,e.resetBtn,e.originalView,e.rebuildTilted,e.rebuildAngle,e.rebuildConfidence,e.rebuildMinRegion,e.rebuildSimplify,e.strength,e.angle,e.confidence,e.minRegion,e.allowTiltedPlanes,e.alignParallel,e.orthogonalSnap,e.sharpIntersections,e.detectThickness,e.edgeProtect,e.legacyStrength,e.legacyAngle,e.legacyMinRegion].forEach(x=>x.disabled=!v)}
function busy(on,stage='Analizando'){e.busy.classList.toggle('hidden',!on);if(stage)e.busyStage.textContent=stage}
function stats(){const v=originalGeometry.attributes.position.count,f=originalGeometry.index?originalGeometry.index.count/3:v/3;e.meshStats.textContent=`${v.toLocaleString('es-AR')} vértices · ${Math.round(f).toLocaleString('es-AR')} caras${duplicateFacesRemoved?` · ${duplicateFacesRemoved} duplicadas eliminadas`:''}`}
function fitCamera(){const g=displayMesh?.geometry;if(!g?.boundingBox)return;const box=g.boundingBox.clone(),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),maxDim=Math.max(size.x,size.y,size.z)||1,dist=maxDim/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov*.5)));camera.near=Math.max(maxDim/10000,.001);camera.far=maxDim*100;camera.position.copy(center).add(new THREE.Vector3(1,.72,1).normalize().multiplyScalar(dist*1.65));camera.updateProjectionMatrix();controls.target.copy(center);controls.update();const grid=scene.getObjectByName('grid');if(grid){grid.scale.setScalar(maxDim/10);grid.position.y=box.min.y-maxDim*.02}}
function runEngine(){if(!originalGeometry?.index)return alert('No pude indexar este mesh.');if(engine==='rebuild')runRebuild();else if(engine==='cad')runCad();else runLegacy()}
function workerBase(path,payload,done,stage){const faceCount=originalGeometry.index.count/3;if(faceCount>800000)return alert(`El análisis está limitado por ahora a 800.000 caras en móvil. Tu modelo tiene ${Math.round(faceCount).toLocaleString('es-AR')}.`);busy(true,stage);e.analyzeBtn.disabled=true;const positions=new Float32Array(originalGeometry.attributes.position.array),indices=originalGeometry.index.array.constructor.from(originalGeometry.index.array),w=new Worker(`${path}?v=${APP_VERSION}`);w.onmessage=({data})=>{if(data.type==='progress'){e.busyStage.textContent=data.stage;return}if(data.type==='error'){w.terminate();busy(false);e.analyzeBtn.disabled=false;alert(data.message);return}if(data.type!=='done')return;done(data);e.resultCard.classList.remove('hidden');e.analyzeBtn.disabled=false;busy(false);w.terminate()};w.onerror=err=>{console.error(err);w.terminate();busy(false);e.analyzeBtn.disabled=false;alert('El procesamiento falló; probablemente faltó memoria disponible.')};w.postMessage({...payload,positions,indices},[positions.buffer,indices.buffer])}
function runRebuild(){workerBase('./rebuild-worker.js',{type:'rebuild',angleDeg:+e.rebuildAngle.value,minRegionFaces:+e.rebuildMinRegion.value,planeConfidence:+e.rebuildConfidence.value/100,simplifyFactor:+e.rebuildSimplify.value/100,allowTiltedPlanes:e.rebuildTilted.checked},data=>{const g=geometryFromPatches(data.patches);install(g);const s=data.stats;e.resultText.textContent=`Rebuild v4 · ${s.patches} superficies nuevas · ${g.attributes.position.count.toLocaleString('es-AR')} vértices finales · ${(s.elapsedMs/1000).toFixed(1)} s`;facts([`${s.sourceRegions} regiones medidas`,`${s.tiltedRejected} inclinadas descartadas`,`${s.openRejected} contornos abiertos descartados`,`topología original: 0% reutilizada`])},'Reconstruyendo desde cero')}
function geometryFromPatches(patches){const pos=[],idx=[];let base=0;for(const p of patches){const outer=p.outer.map(q=>new THREE.Vector2(q[0],q[1])),holes=(p.holes||[]).map(h=>h.map(q=>new THREE.Vector2(q[0],q[1])));let tris;try{tris=THREE.ShapeUtils.triangulateShape(outer,holes)}catch{continue}const all=[...p.outer,...(p.holes||[]).flat()];for(const q of all){const X=p.origin[0]+p.u[0]*q[0]+p.v[0]*q[1],Y=p.origin[1]+p.u[1]*q[0]+p.v[1]*q[1],Z=p.origin[2]+p.u[2]*q[0]+p.v[2]*q[1];pos.push(X,Y,Z)}for(const t of tris)idx.push(base+t[0],base+t[1],base+t[2]);base+=all.length}if(!idx.length)throw new Error('Los contornos detectados no pudieron triangularse.');const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));const C=base>65535?Uint32Array:Uint16Array;g.setIndex(new THREE.BufferAttribute(new C(idx),1));g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g}
function runCad(){workerBase('./mesh-worker.js',{type:'reconstruct',strength:+e.strength.value/100,angleDeg:+e.angle.value,minRegionFaces:+e.minRegion.value,planeConfidence:+e.confidence.value/100,edgeProtection:+e.edgeProtect.value/100,alignParallel:e.alignParallel.checked,orthogonalSnap:e.orthogonalSnap.checked,sharpIntersections:e.sharpIntersections.checked,detectThickness:e.detectThickness.checked,allowTiltedPlanes:e.allowTiltedPlanes.checked},data=>{const g=originalGeometry.clone();g.setAttribute('position',new THREE.BufferAttribute(data.positions,3));g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();install(g);e.resultText.textContent=`v3 · ${data.regions} planos · ${data.verticesMoved.toLocaleString('es-AR')} vértices desplazados · ${(data.elapsedMs/1000).toFixed(1)} s`;facts([`${data.parallelFamilies} familias paralelas`,`${data.rejectedRegions} zonas preservadas`])},'Ejecutando v3')}
function runLegacy(){workerBase('./legacy-worker.js',{type:'clean',strength:+e.legacyStrength.value/100,angleDeg:+e.legacyAngle.value,minRegionFaces:+e.legacyMinRegion.value},data=>{const g=originalGeometry.clone();g.setAttribute('position',new THREE.BufferAttribute(data.positions,3));g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();install(g);e.resultText.textContent=`v2 · ${data.regions} regiones planas · ${data.verticesMoved.toLocaleString('es-AR')} vértices ajustados · ${(data.elapsedMs/1000).toFixed(1)} s`;facts([])},'Ejecutando v2')}
function facts(arr){e.cadFacts.innerHTML='';arr.filter(Boolean).forEach(t=>{const s=document.createElement('span');s.className='cad-fact';s.textContent=t;e.cadFacts.appendChild(s)})}
function exportSTL(){if(!resultGeometry)return;const data=new STLExporter().parse(new THREE.Mesh(resultGeometry),{binary:true});download(new Blob([data],{type:'model/stl'}),`${activeName}_${engine}.stl`)}
function exportOBJ(){if(!resultGeometry)return;const text=new OBJExporter().parse(new THREE.Mesh(resultGeometry));download(new Blob([text],{type:'text/plain'}),`${activeName}_${engine}.obj`)}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}
