import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
import { STLLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/STLLoader.js';
import { OBJLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/OBJLoader.js';
import { GLTFLoader } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/loaders/GLTFLoader.js';
import { STLExporter } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/exporters/STLExporter.js';
import { OBJExporter } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/exporters/OBJExporter.js';
import { mergeGeometries, mergeVertices } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/utils/BufferGeometryUtils.js';

const APP_VERSION='3.1';
const $=id=>document.getElementById(id);
const e={};['viewer','fileInput','openBtn','changeBtn','analyzeBtn','resetBtn','exportStlBtn','exportObjBtn','originalView','cleanView','strength','angle','confidence','edgeProtect','minRegion','alignParallel','orthogonalSnap','sharpIntersections','detectThickness','allowTiltedPlanes','strengthValue','angleValue','confidenceValue','edgeValue','regionValue','busy','busyStage','dropHint','viewerHud','fileName','meshStats','resultCard','resultText','cadFacts','installBtn','versionBadge','cadEngineTab','legacyEngineTab','cadControls','legacyControls','legacyStrength','legacyAngle','legacyMinRegion','legacyStrengthValue','legacyAngleValue','legacyRegionValue'].forEach(id=>e[id]=$(id));
e.versionBadge.textContent=`v${APP_VERSION}`;

let scene,camera,renderer,controls,originalMesh=null,resultMesh=null,originalGeometry=null,resultGeometry=null,activeName='modelo',engine='cad',deferredInstallPrompt=null,reloadingForUpdate=false;
init3D();registerPWA();bindUI();

function makeMaterial(color=0xe7edf3){return new THREE.MeshStandardMaterial({color,roughness:.72,metalness:.02,side:THREE.DoubleSide})}
function init3D(){
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,1,.01,100000);camera.position.set(2.4,1.7,2.8);
 renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;e.viewer.appendChild(renderer.domElement);
 controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;
 scene.add(new THREE.HemisphereLight(0xffffff,0x273445,2.1));const key=new THREE.DirectionalLight(0xffffff,2.3);key.position.set(2,4,3);scene.add(key);const rim=new THREE.DirectionalLight(0x92bfff,1.1);rim.position.set(-3,1,-2);scene.add(rim);
 const grid=new THREE.GridHelper(10,20,0x415165,0x222b36);grid.name='grid';scene.add(grid);
 const resize=()=>{const w=e.viewer.clientWidth||1,h=e.viewer.clientHeight||1;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};new ResizeObserver(resize).observe(e.viewer);resize();
 (function animate(){controls.update();renderer.render(scene,camera);requestAnimationFrame(animate)})();
}
function registerPWA(){
 if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloadingForUpdate)return;reloadingForUpdate=true;location.reload()});window.addEventListener('load',async()=>{try{const r=await navigator.serviceWorker.register(`./sw.js?v=${APP_VERSION}`,{updateViaCache:'none'});await r.update();if(r.waiting)r.waiting.postMessage({type:'SKIP_WAITING'});r.addEventListener('updatefound',()=>{const w=r.installing;if(w)w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)w.postMessage({type:'SKIP_WAITING'})})})}catch(err){console.warn(err)}})}
 window.addEventListener('beforeinstallprompt',x=>{x.preventDefault();deferredInstallPrompt=x;e.installBtn.classList.remove('hidden')});e.installBtn.onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;e.installBtn.classList.add('hidden')};
}
function bindUI(){
 e.openBtn.onclick=()=>e.fileInput.click();e.changeBtn.onclick=()=>e.fileInput.click();e.fileInput.onchange=()=>e.fileInput.files[0]&&loadFile(e.fileInput.files[0]);
 $('fitBtn').onclick=fitCamera;$('wireBtn').onclick=()=>{for(const m of[originalMesh,resultMesh])if(m){m.material.wireframe=!m.material.wireframe;m.material.needsUpdate=true}};
 e.originalView.onclick=()=>showOnly('original');e.cleanView.onclick=()=>showOnly('result');e.cadEngineTab.onclick=()=>setEngine('cad');e.legacyEngineTab.onclick=()=>setEngine('legacy');e.analyzeBtn.onclick=runActiveEngine;e.resetBtn.onclick=resetResult;e.exportStlBtn.onclick=exportSTL;e.exportObjBtn.onclick=exportOBJ;
 const ranges=[[e.strength,e.strengthValue,'%'],[e.angle,e.angleValue,'°'],[e.confidence,e.confidenceValue,'%'],[e.edgeProtect,e.edgeValue,'%'],[e.minRegion,e.regionValue,' caras'],[e.legacyStrength,e.legacyStrengthValue,'%'],[e.legacyAngle,e.legacyAngleValue,'°'],[e.legacyMinRegion,e.legacyRegionValue,' caras']];ranges.forEach(([a,b,s])=>a.oninput=()=>b.value=`${a.value}${s}`);
 ['dragenter','dragover'].forEach(t=>e.viewer.addEventListener(t,x=>{x.preventDefault();e.viewer.parentElement.classList.add('dragging')}));['dragleave','drop'].forEach(t=>e.viewer.addEventListener(t,x=>{x.preventDefault();e.viewer.parentElement.classList.remove('dragging')}));e.viewer.addEventListener('drop',x=>{const f=x.dataTransfer.files[0];if(f)loadFile(f)});
}
function setEngine(mode){engine=mode;e.cadEngineTab.classList.toggle('active',mode==='cad');e.legacyEngineTab.classList.toggle('active',mode==='legacy');e.cadControls.classList.toggle('hidden',mode!=='cad');e.legacyControls.classList.toggle('hidden',mode!=='legacy');e.analyzeBtn.textContent=mode==='cad'?'Mesh → CAD':'Aplicar Planar Cleanup';resetResult();setControlsEnabled(!!originalGeometry)}
async function loadGLTF(buffer,ext){const loader=new GLTFLoader(),payload=ext==='gltf'?new TextDecoder().decode(buffer):buffer,gltf=await new Promise((res,rej)=>loader.parse(payload,'',res,rej));gltf.scene.updateMatrixWorld(true);const geos=[];gltf.scene.traverse(c=>{if(!c.isMesh||!c.geometry?.attributes?.position)return;let g=c.geometry.clone();if(g.index)g=g.toNonIndexed();const f=new THREE.BufferGeometry();f.setAttribute('position',g.attributes.position.clone());f.applyMatrix4(c.matrixWorld);geos.push(f)});if(!geos.length)throw new Error('El GLB/GLTF no contiene meshes.');return geos.length===1?geos[0]:mergeGeometries(geos,false)}
async function loadFile(file){
 const ext=file.name.split('.').pop().toLowerCase();if(!['stl','obj','glb','gltf'].includes(ext))return alert('3DLab acepta GLB, GLTF, STL y OBJ.');setBusy(true,'Abriendo modelo');
 try{const buffer=await file.arrayBuffer();let g;if(ext==='stl')g=new STLLoader().parse(buffer);else if(ext==='obj'){const obj=new OBJLoader().parse(new TextDecoder().decode(buffer));obj.updateMatrixWorld(true);const gs=[];obj.traverse(c=>{if(!c.isMesh||!c.geometry?.attributes?.position)return;const x=new THREE.BufferGeometry();x.setAttribute('position',c.geometry.attributes.position.clone());x.applyMatrix4(c.matrixWorld);gs.push(x)});if(!gs.length)throw new Error('El OBJ no contiene meshes.');g=gs.length===1?gs[0]:mergeGeometries(gs,false)}else g=await loadGLTF(buffer,ext);g=normalizeGeometry(g);clearSceneMeshes();originalGeometry=g;activeName=file.name.replace(/\.[^.]+$/,'');originalMesh=new THREE.Mesh(originalGeometry,makeMaterial());scene.add(originalMesh);e.dropHint.classList.add('hidden');e.viewerHud.classList.remove('hidden');e.fileName.textContent=file.name;updateStats();setControlsEnabled(true);showOnly('original');fitCamera();e.resultCard.classList.add('hidden')}catch(err){console.error(err);alert(`No pude abrir el modelo: ${err.message}`)}finally{setBusy(false)}
}
function normalizeGeometry(input){let g=new THREE.BufferGeometry();g.setAttribute('position',input.attributes.position.clone());g=mergeVertices(g,1e-5);g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g}
function clearSceneMeshes(){for(const m of[originalMesh,resultMesh])if(m){scene.remove(m);m.material.dispose()}originalGeometry?.dispose();resultGeometry?.dispose();originalMesh=resultMesh=null;originalGeometry=resultGeometry=null}
function showOnly(which){if(originalMesh)originalMesh.visible=which==='original';if(resultMesh)resultMesh.visible=which==='result';e.originalView.classList.toggle('active',which==='original');e.cleanView.classList.toggle('active',which==='result')}
function installResultGeometry(g){if(resultMesh){scene.remove(resultMesh);resultMesh.material.dispose();resultGeometry?.dispose()}resultGeometry=g;resultMesh=new THREE.Mesh(g,makeMaterial(0xdde8f2));scene.add(resultMesh);resultMesh.visible=false;e.cleanView.disabled=false;e.exportStlBtn.disabled=false;e.exportObjBtn.disabled=false;showOnly('result')}
function resetResult(){if(resultMesh){scene.remove(resultMesh);resultMesh.material.dispose();resultMesh=null}resultGeometry?.dispose();resultGeometry=null;if(originalMesh)showOnly('original');e.cleanView.disabled=true;e.exportStlBtn.disabled=true;e.exportObjBtn.disabled=true;e.resultCard.classList.add('hidden')}
function setControlsEnabled(v){[e.changeBtn,e.analyzeBtn,e.resetBtn,e.originalView,e.strength,e.angle,e.confidence,e.edgeProtect,e.minRegion,e.alignParallel,e.orthogonalSnap,e.sharpIntersections,e.detectThickness,e.allowTiltedPlanes,e.legacyStrength,e.legacyAngle,e.legacyMinRegion].forEach(x=>x.disabled=!v)}
function setBusy(on,stage='Analizando topología'){e.busy.classList.toggle('hidden',!on);e.busyStage.textContent=stage}
function updateStats(){const v=originalGeometry.attributes.position.count,f=originalGeometry.index?originalGeometry.index.count/3:v/3;e.meshStats.textContent=`${v.toLocaleString('es-AR')} vértices · ${Math.round(f).toLocaleString('es-AR')} caras`}
function fitCamera(){const g=(resultMesh?.visible?resultGeometry:originalGeometry);if(!g?.boundingBox)return;const box=g.boundingBox.clone(),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),maxDim=Math.max(size.x,size.y,size.z)||1,dist=maxDim/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov*.5)));camera.near=Math.max(maxDim/10000,.001);camera.far=maxDim*100;camera.position.copy(center).add(new THREE.Vector3(1,.72,1).normalize().multiplyScalar(dist*1.65));camera.updateProjectionMatrix();controls.target.copy(center);controls.update();const grid=scene.getObjectByName('grid');if(grid){grid.scale.setScalar(maxDim/10);grid.position.y=box.min.y-maxDim*.02}}
function runActiveEngine(){if(!originalGeometry?.index)return alert('No pude indexar este mesh.');engine==='cad'?runCad():runLegacy()}
function startWorker(path,payload,onDone){const faceCount=originalGeometry.index.count/3;if(faceCount>800000)return alert(`Este motor experimental limita el análisis a 800.000 caras en móvil. El modelo tiene ${Math.round(faceCount).toLocaleString('es-AR')}.`);setBusy(true,engine==='cad'?'Detectando planos y eje 2.5D':'Ejecutando motor v2');e.analyzeBtn.disabled=true;const positions=new Float32Array(originalGeometry.attributes.position.array),indices=originalGeometry.index.array.constructor.from(originalGeometry.index.array),w=new Worker(`${path}?v=${APP_VERSION}`);w.onmessage=({data})=>{if(data.type==='progress'){e.busyStage.textContent=data.stage;return}if(data.type==='error'){w.terminate();setBusy(false);e.analyzeBtn.disabled=false;alert(data.message);return}if(data.type!=='done')return;const g=originalGeometry.clone();g.setAttribute('position',new THREE.BufferAttribute(data.positions,3));g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();installResultGeometry(g);onDone(data);e.resultCard.classList.remove('hidden');e.analyzeBtn.disabled=false;setBusy(false);w.terminate()};w.onerror=err=>{console.error(err);w.terminate();setBusy(false);e.analyzeBtn.disabled=false;alert('El procesamiento falló; probablemente faltó memoria disponible.')};w.postMessage({...payload,positions,indices},[positions.buffer,indices.buffer])}
function runCad(){startWorker('./mesh-worker.js',{type:'reconstruct',strength:+e.strength.value/100,angleDeg:+e.angle.value,minRegionFaces:+e.minRegion.value,planeConfidence:+e.confidence.value/100,edgeProtection:+e.edgeProtect.value/100,alignParallel:e.alignParallel.checked,orthogonalSnap:e.orthogonalSnap.checked,sharpIntersections:e.sharpIntersections.checked,detectThickness:e.detectThickness.checked,allowTiltedPlanes:e.allowTiltedPlanes.checked},data=>{e.resultText.textContent=`${data.regions} planos · ${data.orthogonalEdges} intersecciones rectificadas · ${data.verticesMoved.toLocaleString('es-AR')} vértices corregidos · ${(data.elapsedMs/1000).toFixed(1)} s`;e.cadFacts.innerHTML='';const facts=[`${data.parallelFamilies} familias paralelas`,`${data.rejectedRegions} zonas ambiguas preservadas`,data.extrusionAxis?`eje 2.5D inferido`:''];if(data.tiltedRejected)facts.push(`${data.tiltedRejected} planos inclinados descartados`);if(data.thicknesses?.length)facts.push(`espesores: ${data.thicknesses.join(' / ')}`);facts.filter(Boolean).forEach(t=>{const s=document.createElement('span');s.className='cad-fact';s.textContent=t;e.cadFacts.appendChild(s)})})}
function runLegacy(){startWorker('./legacy-worker.js',{type:'clean',strength:+e.legacyStrength.value/100,angleDeg:+e.legacyAngle.value,minRegionFaces:+e.legacyMinRegion.value},data=>{e.resultText.textContent=`Motor v2 · ${data.regions} regiones planas · ${data.verticesMoved.toLocaleString('es-AR')} vértices ajustados · ${(data.elapsedMs/1000).toFixed(1)} s`;e.cadFacts.innerHTML=''})}
function exportSTL(){if(!resultGeometry)return;const data=new STLExporter().parse(new THREE.Mesh(resultGeometry),{binary:true});downloadBlob(new Blob([data],{type:'model/stl'}),`${activeName}_${engine==='cad'?'mesh_to_cad':'planar_v2'}.stl`)}
function exportOBJ(){if(!resultGeometry)return;const text=new OBJExporter().parse(new THREE.Mesh(resultGeometry));downloadBlob(new Blob([text],{type:'text/plain'}),`${activeName}_${engine==='cad'?'mesh_to_cad':'planar_v2'}.obj`)}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
